require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "examples/*.rb"
    - vendor/**/*

#
# Opinionated cops
#

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

#
# Disabled cops
#

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Style/Proc:
  Enabled: false
